[palette]
background = "#05181d"
foreground = "#eee8d5"
black = "#657b83"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"
bright_black = "#72898f"
bright_red = "#ff5e56"
bright_green = "#83c746"
bright_yellow = "#efc541"
bright_blue = "#4f9cfe"
bright_magenta = "#ff81ca"
bright_cyan = "#56d8c9"
bright_white = "#fbf0cc"
cursor_color = "#839496"
cursor_text = "#002b36"
selection_background = "#002b36"
selection_foreground = "#eee8d5"
