theme = "base16_terminal"

[editor]
auto-pairs = false
bufferline = "always"
cursorline = true
default-yank-register = "+"
end-of-line-diagnostics = "warning"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
display-progress-messages = true

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
D = ["kill_to_line_end"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
esc = ["collapse_selection", "keep_primary_selection"]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]

[keys.normal.space]
q = ":buffer-close"
 
[keys.normal.space.z]
c = ":clipboard-yank"
l = ":log-open"
p = ":sh echo \"%{buffer_name}\" | pbcopy"
r = ":reload"

# <backspace> for zellij commands
[keys.normal.backspace]
b = ":sh zellij run --close-on-exit -f -x=1%% -y=4%% --width=99%% --height=92%% -- tig blame \"%{buffer_name}\""
h = ":sh zellij run --close-on-exit -f -x=1%% -y=4%% --width=99%% --height=92%% -- lazygit --filter \"%{buffer_name}\""

[keys.insert]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
