theme = "darkstar"

[editor]
bufferline = "always"
cursorline = true
end-of-line-diagnostics = "warning"

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]

