[[language]]
name = "css"
formatter = { command = "npx", args = ["prettier", "--parser", "css"] }
language-servers = [
  "vscode-css-language-server",
  "emmet-lsp",
  "tailwindcss-ls"
]

[[language]]
name = "git-commit"
rulers = []

[[language]]
name = "html"
language-servers = [
  "tailwindcss-ls",
  "vscode-html-language-server",
  "emmet-lsp"
]

[[language]]
name = "tsx"
language-servers = [
  "vscode-eslint-language-server",
  "tailwindcss-ls",
  "typescript-language-server"
]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]
