[[language]]
name = "css"
formatter = { command = "npx", args = ["prettier", "--parser", "css"] }
language-servers = [
  "vscode-css-language-server",
  "tailwindcss-ls"
]

[[language]]
name = "git-commit"
rulers = []

[[language]]
name = "html"
language-servers = [
  "tailwindcss-ls",
  "vscode-html-language-server"
]

[[language]]
name = "lua"
file-types = ["p8"]
language-servers = ["pico8-ls"]

[language-server.pico8-ls]
command = "pico8-ls"

[[language]]
name = "tsx"
language-servers = [
  "vscode-eslint-language-server",
  "tailwindcss-ls",
  "typescript-language-server"
]

[language-server.csharp]
command = "csharp-ls"
environment = { DOTNET_ROOT = "/opt/homebrew/Cellar/dotnet/10.0.102/libexec" }

[[language]]
name = "c-sharp"
language-servers = ["csharp"]
file-types = ["cs"]

