[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij -l welcome"]

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 8, y= 8 }

[colors.primary]
#background = "#032029"
background = "#06171d"

[colors.cursor]
text = "#002b36"
cursor = "#839496"

[colors.normal]
black   = "#032029"
red     = "#d21d25"
green   = "#728a06"
yellow  = "#a57806"
blue    = "#2175c6"
magenta = "#c61d6e"
cyan    = "#269287"
white   = "#fdf4dd"

[colors.bright]
black   = "#053d48"
red     = "#fd564e"
green   = "#80b83c"
yellow  = "#e3b230"
blue    = "#0096f5"
magenta = "#f176bd"
cyan    = "#39c7b9"
white   = "#fef3da"

[font]
size = 18

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
y = 2

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
key = "ArrowLeft"
mods = "Option"
chars = "\u001bb"

[[keyboard.bindings]]
key = "ArrowRight"
mods = "Option"
chars = "\u001bf"

[[keyboard.bindings]]
chars = "\u001bn"
mods = "Command"
key = "N"

[[keyboard.bindings]]
mods = "Command"
key = "T"
chars = "\u001bt"

[[keyboard.bindings]]
chars = "\u001bw"
mods = "Command"
key = "W"


