[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij -l welcome"]

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 8, y= 8 }
opacity = 1.0

[colors.primary]
background = "#05181d"
foreground = "#EEE8D5"

[colors.cursor]
text = "#002b36"
cursor = "#839496"

[colors.normal]
black   = "#002b36"
red     = "#dc322f"
green   = "#859900"
yellow  = "#b58900"
blue    = "#268bd2"
magenta = "#d33682"
cyan    = "#2aa198"
white   = "#EEE8D5"

[colors.bright]
black   = "#153944"
red     = "#ff5e56"
green   = "#83c746"
yellow  = "#efc541"
blue    = "#4f9cfe"
magenta = "#ff81ca"
cyan    = "#56d8c9"
white   = "#fbf0cc"

[font]
size = 18

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
y = 2

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
key = "ArrowLeft"
mods = "Option"
chars = "\u001bb"

[[keyboard.bindings]]
key = "ArrowRight"
mods = "Option"
chars = "\u001bf"

[[keyboard.bindings]]
chars = "\u001bn"
mods = "Command"
key = "N"

[[keyboard.bindings]]
mods = "Command"
key = "F"
chars = "\u001bg"

[[keyboard.bindings]]
mods = "Command"
key = "T"
chars = "\u001bt"

[[keyboard.bindings]]
chars = "\u001bw"
mods = "Command"
key = "W"


