[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij -l welcome"]

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 8, y= 8 }

[colors.primary]
#background = "#032029"
background = "#06171d"

[colors.cursor]
text = "#002b36"
cursor = "#839496"

[colors.normal]
black   = "#032029"
red     = "#d21d25"
green   = "#728a06"
yellow  = "#a57806"
blue    = "#2175c6"
magenta = "#c61d6e"
cyan    = "#269287"
white   = "#fdf4dd"

[colors.bright]
black   = "#4a5f66"
red     = "#690f16"
green   = "#343b0e"
yellow  = "#4b340e"
blue    = "#1a3352"
magenta = "#5b1431"
cyan    = "#1a3e3a"
white   = "#fdf4dd"

[font]
size = 18

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
y = 2

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
key = "ArrowLeft"
mods = "Option"
chars = "\u001bb"

[[keyboard.bindings]]
key = "ArrowRight"
mods = "Option"
chars = "\u001bf"

[[keyboard.bindings]]
chars = "\u001bn"
mods = "Command"
key = "N"

[[keyboard.bindings]]
mods = "Command"
key = "T"
chars = "\u001bt"

[[keyboard.bindings]]
chars = "\u001bw"
mods = "Command"
key = "W"


