[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-l", "-c", "zellij -l welcome"]

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 8, y= 8 }
opacity = 1.0
option_as_alt = "Both"

[font]
size = 18

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
y = 2

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001b\u007f"
key = "Back"
mods = "Alt"

